public enum ApplyType
{
    ETC,
    
    // 주민 등록증
    ISSUANCE_REGISTRATION_CARD,
    // 주민등록등본
    ISSUANCE_CERTIFIED_RESIDENT_REGISTRATION,
    // 여권
    ISSUANCE_PASSPORT,
    // 상담
    COUNSEL,

    // 재학 증명서
    ISSUANCE_CERTIFICATE_ENROLLMENT,
    // 졸업 증명서
    ISSUANCE_CERTIFICATE_GRADUATION,
    // 휴학 증명서
    ISSUANCE_CERIFICATE_LEAVEOFABSENCE,
    // 납입 증명서
    ISSUANCE_CERTIFICATE_PAYMENT,

    // 국가기술자격증
    TECHNICAL_QUALIFICATION,
    // 취업 특강
    EMPLOYMENT_SPECIAL_LECTURE,
    // 보건증
    ISSUACNE_CERTIFICATE_HEALTH,
    // 고용보험 이력
    ISSUANCE_EMPLOYMENT_ISURANCE_HISTORY,

}